---
language: go
go:
- tip
- 1.13.x
- 1.12.x
- 1.11.x
- 1.10.x
- 1.9.x
- 1.8.x
sudo: false

env:
  global:
  - GO111MODULE=on

go_import_path: github.com/dolmen-go/semver

before_install:
# Show package path
- GO111MODULE=off go list

install:
# Fetch dependencies:
# - go < 1.11:  go get -t -v ./...
# - go >= 1.11: go list -test -mod=readonly
- "case \"$(go version)\" in (*' go1.'[02-9]*|*' go1.10.'*) go get -t -v ./... ;; (*) go list -test -mod=readonly ;; esac"

script:
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
